package org.zsample.claimssampleprocess;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(04c22fc481cfa75c4fdab655ea3bf34e)
 */
public class Claims  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Float claimAmount;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Boolean claimValid;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String customerName;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String reason;

    public Claims() {
    }

    public Claims(java.lang.String customerName, java.lang.Float claimAmount, java.lang.String reason, java.lang.Boolean claimValid) {
        this.customerName = customerName;
        this.claimAmount = claimAmount;
        this.reason = reason;
        this.claimValid = claimValid;
    }


    
    public java.lang.Float getClaimAmount() {
        return this.claimAmount;
    }

    public void setClaimAmount(java.lang.Float claimAmount) {
        this.claimAmount = claimAmount;
    }
    
    public java.lang.Boolean getClaimValid() {
        return this.claimValid;
    }

    public void setClaimValid(java.lang.Boolean claimValid) {
        this.claimValid = claimValid;
    }
    
    public java.lang.String getCustomerName() {
        return this.customerName;
    }

    public void setCustomerName(java.lang.String customerName) {
        this.customerName = customerName;
    }
    
    public java.lang.String getReason() {
        return this.reason;
    }

    public void setReason(java.lang.String reason) {
        this.reason = reason;
    }
}